name: 'Aging'

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to age you
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: New Age step
      id: newage
      uses: index.js
      with:
        your-name: 'Leesa Marie'
        your-age: '20'
        timespan: '10'

