
name: 'Aging2'

on: [push]

jobs:  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: run
      run: node action.js
        with:
          your-name: ${{ secrets.name }}
          your-age: ${{ secrets.age }}
          timespan: '10'



